models:
  - id: microsoft/phi-3-mini-4k-instruct
    name: phi3
    adapter: results/models/phi3_lora_v2/adapter
  - id: Qwen/Qwen2.5-3B-Instruct
    name: qwen25_3b
    adapter: results/models/qwen3_lora_v2/adapter
  - id: microsoft/Phi-3.5-mini-instruct   # or mistralai/Mistral-7B-Instruct-v0.2
    name: phi35mini                       # or mistral7b
    adapter: results/models/phi35_lora_v2/adapter  # or mistral7b_lora_v2/adapter

rag:
  top_k: 3
  max_bullets: 6

verifier:
  threshold: 0.64   # start a bit higher for cascade/router

policy:
  mode: cascade               # you’ll run all three modes anyway
  order: [phi3, qwen25_3b, phi35mini]    # cheap → strong
  ensemble_size: 2